In [14]:
### numerical processing
import numpy as np
###text preprocessing
import pandas as pd
from collections import  Counter
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from string import punctuation
import networkx
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
# nltk.download('wordnet')
from nltk.stem.wordnet import WordNetLemmatizer
###text visualization
import seaborn as sns



In [20]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [16]:
import dash
import dash_core_components
import dash_html_components
import dash.dependencies

In [21]:
cached_stopword_list=stopwords.words('english')  ### performance 
train_data=pd.read_csv('Datasets/train.csv')
print(train_data['answer'][3])
test_data=pd.read_csv('Datasets/test.csv')
print(test_data['answer'][3])

# print(cached_stopword_list)


Sending an "affidavit" it is a dispute between Rashi and Rabbeinu Tam.

Devarim 19:15:


  לא יקום עד אחד באיש לכל עון ולכל חטאת בכל חטא אשר יחטא על פי שני עדים או על פי שלשה עדים יקום דבר


Rashi:


  ולא שיכתבו עדותם באגרת וישלחו לבית דין
  
  And not that they write their testimony in a letter and send it to Beis Din


Tosefos Bava Basra 40a (continued from 39b):


  ועוד אומר ר"י ששמע מן ר"ת שנוהגים לשלח העדים עדותם באיגרת לב"ד וחשיב עדות והא דדרשינן בספרי. מפיהם ולא מפי כתבם לא אתא אלא למעוטי דוקא אלם שאינו בר הגדה אבל ראוי להגדה אין הגדה מעכבת בו 
  
  R"i said that he heard from Rabbeinu Tam that the custom is to send testimony by a letter and it is considered [valid] testimony.  And that which it expounds in the Sifre "From their mouths and not from their writing" is only coming to exclude a mute who is not able to speak, but someone who is able to speak does not need to speak.


Rambam concludes it is not allowed, but in monetary law the Chachomim enacted that it would be acce

In [22]:
def keras_tokenization(dataframe):
    
    answer_list=[]
    tokens_list=[]
    for row in dataframe['answer']:
#         print(row)
        tokens=text_to_word_sequence(row,filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r') ## adding \r 
#         print(tokens)
        filtered_sentence=' '.join([word for word in tokens if not word in cached_stopword_list])
        filtered_tokens=[word for word in tokens if not word in cached_stopword_list]
#         print(filtered_sentence)
#         print(filtered_tokens)
        answer_list.append(filtered_sentence)
        tokens_list.append(filtered_tokens)
      
    
    dataframe['answer_tokens']=tokens_list
    dataframe['answer_sentence']=answer_list    
    return dataframe

In [23]:
keras_tokenization(train_data)


qa_id                                     question_title  \
0         0  What am I losing when using extension tubes in...   
1         1  What is the distinction between a city and a s...   
2         2  Maximum protusion length for through-hole comp...   
3         3              Can an affidavit be used in Beit Din?   
4         5       How do you make a binary image in Photoshop?   
...     ...                                                ...   
6074   9642               Using a ski helmet for winter biking   
6075   9643  Adjustment to road bike brakes for high grade ...   
6076   9645  Suppress 'file truncated' messages when using ...   
6077   9646           When should a supervisor be a co-author?   
6078   9647  Why are there so many different types of screw...   

                                          question_body question_user_name  \
0     After playing around with macro photography on...               ysap   
1     I am trying to understand what kinds of places...      russellpierce   
2     I'm working on a PCB that has through-hole com...          Joe Baker   
3     An affidavit, from what i understand, is basic...         Scimonster   
4     I am trying to make a binary image. I want mor...            leigero   
...                                                 ...                ...   
6074  I am curious if anyone uses a skiing helmet fo...   sixtyfootersdude   
6075  I have a road bike with a front brake that wea...                ash   
6076  I'm tailing a log file using tail -f messages....    Maneating Koala   
6077  What are people's views on this?  To be specif...                MrB   
6078  Newbie question.\r\n\r\nWhy is it that there's...            Doug T.   

                                     question_user_page  \
0            https://photo.stackexchange.com/users/1024   
1              https://rpg.stackexchange.com/users/8774   
2     https://electronics.stackexchange.com/users/10157   
3          https://judaism.stackexchange.com/users/5151   
4     https://graphicdesign.stackexchange.com/users/...   
...                                                 ...   
6074       https://bicycles.stackexchange.com/users/134   
6075     https://bicycles.stackexchange.com/users/14519   
6076         https://unix.stackexchange.com/users/60445   
6077                https://mathoverflow.net/users/2189   
6078            https://diy.stackexchange.com/users/321   

                                                 answer answer_user_name  \
0     I just got extension tubes, so here's the skin...           rfusca   
1     It might be helpful to look into the definitio...     Erik Schmidt   
2     Do you even need grooves?  We make several pro...      Dwayne Reid   
3     Sending an "affidavit" it is a dispute between...    Y     e     z   
4     Check out Image Trace in Adobe Illustrator. \r...             q2ra   
...                                                 ...              ...   
6074  If you're thinking about wearing a ski helmet ...         Matt Leo   
6075  \r\nYou can replace the pads (as stated elsewh...   Daniel R Hicks   
6076  Maybe help if can be fixes origin of this erro...         BG Bruno   
6077  As a non-mathematician, I am somewhat mystifie...           angela   
6078  First, I really like Eric's answer for practic...         Scivitri   

                                       answer_user_page  \
0            https://photo.stackexchange.com/users/1917   
1              https://rpg.stackexchange.com/users/1871   
2     https://electronics.stackexchange.com/users/64754   
3          https://judaism.stackexchange.com/users/4794   
4     https://graphicdesign.stackexchange.com/users/...   
...                                                 ...   
6074      https://bicycles.stackexchange.com/users/3340   
6075      https://bicycles.stackexchange.com/users/1584   
6076         https://unix.stackexchange.com/users/68208   
6077                https://mathoverflow.net/users/4267   
6078 

## Kaggle best approaches
###  https://www.kaggle.com/rahulvv/bidirectional-lstm-glove200d '''
''' import string
import re

### remove urls
def remove_urls(text):
    url = re.compile(r'https?://\S+|www\.\S+')
    return url.sub(r'',text)
  
#remove html tags
def remove_html(text):
    html=re.compile(r'<.*?>')
    return html.sub(r'',text)

### splitting the text
def split_text(text):
    text = text.split()
    return text

### making lower case words
def lower(text):
    text = [word.lower() for word in text]
    return str(text)

### remove punct
def remove_punct(text):
    text = ''.join([char for char in text if char not in string.punctuation])
    text = re.sub('[0-9]+', '', str(text))
    return text

## remove stopwords
def remove_stopwords(text):
    pattern = re.compile(r'\b('+r'|'.join(stopwords.words('english')) + r')\b\s*')
    text = pattern.sub(' ', text)
    return text

## lemmatization
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    text = lemmatizer.lemmatize(text)
    return text


def final(text):
    t0 = remove_urls(text)
    t1 = remove_html(t0)
    t2 = split_text(t1)
    t3 = lower(t2)
    t4 = remove_punct(t3)
    t5 = remove_stopwords(t4)
    t6 = lemmatize_words(t5)
    return t6

train_sentences = train_data.question_body.values

#### train_labels = train_df.target.values
test_sentences = test_data.question_body.values
training_sentences = []
for i in range(len(train_sentences)):
    data = final(train_sentences[i])
    training_sentences.append(data)

testing_sentences = []
for i in range(len(test_sentences)):
    data = final(test_sentences[i])
    testing_sentences.append(data)
print(training_sentences[1])  '''

In [36]:
def keras_tokenization(text):
    sent_list=[]
    tokens_list=[]
    for row in text:
        tokens=text_to_word_sequence(row,filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r') ## adding \r 
        filtered_sentence=' '.join([word for word in tokens if not word in cached_stopword_list])
        filtered_tokens=[word for word in tokens if not word in cached_stopword_list]
        sent_list.append(filtered_sentence)
        tokens_list.append(filtered_tokens)
    return sent_list,tokens_list

In [37]:
question_text=train_data.question_body
# question_sent,question_tokens=keras_tokenization(question_text)
train_data['question_sent'],train_data['question_tokens']=keras_tokenization(question_text)


In [38]:
train_data

qa_id                                     question_title  \
0         0  What am I losing when using extension tubes in...   
1         1  What is the distinction between a city and a s...   
2         2  Maximum protusion length for through-hole comp...   
3         3              Can an affidavit be used in Beit Din?   
4         5       How do you make a binary image in Photoshop?   
...     ...                                                ...   
6074   9642               Using a ski helmet for winter biking   
6075   9643  Adjustment to road bike brakes for high grade ...   
6076   9645  Suppress 'file truncated' messages when using ...   
6077   9646           When should a supervisor be a co-author?   
6078   9647  Why are there so many different types of screw...   

                                          question_body question_user_name  \
0     After playing around with macro photography on...               ysap   
1     I am trying to understand what kinds of places...      russellpierce   
2     I'm working on a PCB that has through-hole com...          Joe Baker   
3     An affidavit, from what i understand, is basic...         Scimonster   
4     I am trying to make a binary image. I want mor...            leigero   
...                                                 ...                ...   
6074  I am curious if anyone uses a skiing helmet fo...   sixtyfootersdude   
6075  I have a road bike with a front brake that wea...                ash   
6076  I'm tailing a log file using tail -f messages....    Maneating Koala   
6077  What are people's views on this?  To be specif...                MrB   
6078  Newbie question.\r\n\r\nWhy is it that there's...            Doug T.   

                                     question_user_page  \
0            https://photo.stackexchange.com/users/1024   
1              https://rpg.stackexchange.com/users/8774   
2     https://electronics.stackexchange.com/users/10157   
3          https://judaism.stackexchange.com/users/5151   
4     https://graphicdesign.stackexchange.com/users/...   
...                                                 ...   
6074       https://bicycles.stackexchange.com/users/134   
6075     https://bicycles.stackexchange.com/users/14519   
6076         https://unix.stackexchange.com/users/60445   
6077                https://mathoverflow.net/users/2189   
6078            https://diy.stackexchange.com/users/321   

                                                 answer answer_user_name  \
0     I just got extension tubes, so here's the skin...           rfusca   
1     It might be helpful to look into the definitio...     Erik Schmidt   
2     Do you even need grooves?  We make several pro...      Dwayne Reid   
3     Sending an "affidavit" it is a dispute between...    Y     e     z   
4     Check out Image Trace in Adobe Illustrator. \r...             q2ra   
...                                                 ...              ...   
6074  If you're thinking about wearing a ski helmet ...         Matt Leo   
6075  \r\nYou can replace the pads (as stated elsewh...   Daniel R Hicks   
6076  Maybe help if can be fixes origin of this erro...         BG Bruno   
6077  As a non-mathematician, I am somewhat mystifie...           angela   
6078  First, I really like Eric's answer for practic...         Scivitri   

                                       answer_user_page  \
0            https://photo.stackexchange.com/users/1917   
1              https://rpg.stackexchange.com/users/1871   
2     https://electronics.stackexchange.com/users/64754   
3          https://judaism.stackexchange.com/users/4794   
4     https://graphicdesign.stackexchange.com/users/...   
...                                                 ...   
6074      https://bicycles.stackexchange.com/users/3340   
6075      https://bicycles.stackexchange.com/users/1584   
6076         https://unix.stackexchange.com/users/68208   
6077                https://mathoverflow.net/users/4267   
6078 

In [25]:
# print(question_tokens[0])

In [26]:
# print(question_sent[0])

## breaking into modules



In [39]:
def tokenization(text):
    return(text_to_word_sequence(text,filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r'))
print(tokenization(question_text[0]))
tokens=tokenization(question_text[0])

def stopword_removal(text):
    return(' '.join([word for word in text if not word in cached_stopword_list]))
print(stopword_removal(tokens))

['after', 'playing', 'around', 'with', 'macro', 'photography', 'on', 'the', 'cheap', 'read', 'reversed', 'lens', 'rev', 'lens', 'mounted', 'on', 'a', 'straight', 'lens', 'passive', 'extension', 'tubes', 'i', 'would', 'like', 'to', 'get', 'further', 'with', 'this', 'the', 'problems', 'with', 'the', 'techniques', 'i', 'used', 'is', 'that', 'focus', 'is', 'manual', 'and', 'aperture', 'control', 'is', 'problematic', 'at', 'best', 'this', 'limited', 'my', 'setup', 'to', 'still', 'subjects', 'read', 'dead', 'insects', 'now', 'as', 'spring', 'is', 'approaching', 'i', 'want', 'to', 'be', 'able', 'to', 'shoot', 'live', 'insects', 'i', 'believe', 'that', 'for', 'this', 'autofocus', 'and', 'settable', 'aperture', 'will', 'be', 'of', 'great', 'help', 'so', 'one', 'obvious', 'but', 'expensive', 'option', 'is', 'a', 'macro', 'lens', 'say', 'ef', '100mm', 'macro', 'however', 'i', 'am', 'not', 'really', 'interested', 'in', 'yet', 'another', 'prime', 'lens', 'an', 'alternative', 'is', 'the', 'electrica

In [40]:

question_text_sent_list=[]
answer_text_sent_list=[]

for i in train_data['question_body']:
    quest_tokens=tokenization(i)
    quest_sent=stopword_removal(quest_tokens)
#     print(quest_sent)
    
    question_text_sent_list.append(quest_sent)
# print((question_text_sent_list[:5])) 


for i in train_data['answer']:
    ans_tokens=tokenization(i)
    ans_sent=stopword_removal(quest_tokens)
    answer_text_sent_list.append(quest_sent)


### benchmarking each step using time function and creating logs and saving logs 

In [42]:
### Glove Model running
word2vec = {}
with open('/Kaggle-Google-QUEST-QA-Labeling/Vectors/glove.6B.200d.txt',encoding='utf-8') as vec_file:
    for line in vec_file:
        values=line.split()
#         print(values)
        words=values[0]
        vec = np.asarray(values[1:], dtype='float32') 
        word2vec[words]=vec
    print('Found %s word vectors.' % len(word2vec))
        


Found 400000 word vectors.


In [29]:
print(type(word2vec))

<class 'dict'>


In [60]:
num_words = 200
embedding_dim = 200
max_length = 32
trunc_type='post'
padding_type='post'
oov_tok = 'OOV'

In [61]:

tokenizer=Tokenizer(num_words=num_words, oov_token=oov_tok)
tokenizer.fit_on_texts(question_text_sent_list)

question_text_seq=tokenizer.texts_to_sequences(question_text_sent_list)
# print('Question_text_sequence:',question_text_seq)

word_index = tokenizer.word_index
print('Total unique tokens generated: ',len(word_index))

padded_train = pad_sequences(sequences=question_text_seq, maxlen=max_length, padding=padding_type, truncating=trunc_type)
print('Padded Sequences:',padded_train)
print('Shape of padded train tensor: ', padded_train.shape)

Total unique tokens generated:  30528
Padded Sequences: [[  1   1   1 ...   1  87   1]
 [ 80 160   1 ...   1   1  11]
 [  9 131   1 ...   1  67   1]
 ...
 [  9   1 187 ...   1   1   1]
 [  1   1   1 ...   1   1  53]
 [  1  29   1 ...   0   0   0]]
Shape of padded train tensor:  (6079, 32)


In [62]:
num_words = min(20000, len(word_index)+1)
print(num_words)

embedding_matrix = np.zeros((num_words, embedding_dim))
print(np.shape(embedding_matrix))

20000
(20000, 200)


In [69]:

embeddings = []
for word, i in word_index.items():
    
    if i<num_words:
        embeddings = word2vec.get(word)
        if embeddings is not None:
            embedding_matrix[i] = embeddings
            
        
# print(embedding_matrix[1])            
# print(np.shape(embedding_matrix))